apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $val := .Values.configFiles }}
  {{ $key }}: |
{{ $val | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-spi
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $val := .Values.spiFiles }}
  {{ $key }}: |
{{ $val | indent 4 }}
{{- end }}
